### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by nyxymuffin** [Myvar/CosmosELF#2]
Documentation? If its there I cant find it....

**Comment by Myvar** [comment]
I highly dought this code even works any more lol, was more of an experiment, but if your brave(or bord) to the point of getting it working, there is example code here:
https://github.com/Myvar/CosmosELF/blob/master/CosmosELF/Kernel.cs#L25

**Comment by nyxymuffin** [comment]
Epic. I'm sure I can keep it working
